{% set name = "ipymidicontrols" %}
{% set version = "0.1.3" %}
{% set hash = "797f6704160cfdb220b604120eebf2d93b506a7e516d8866dedbddf46fc73b81" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - ipywidgets >=7

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipymidicontrols
    - ipymidicontrols.tests

about:
  home: http://github.com/jupyter-widgets/midicontrols
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'MIDI controllers for ipywidgets'
  description: |
    ipymidicontrols enables MIDI controllers to be used as ipywidgets input
    and output devices.
  doc_url: http://ipymidicontrols.readthedocs.io/
  dev_url: https://github.com/jupyter-widgets/ipymidicontrols

extra:
  recipe-maintainers:
    - jasongrout
    - SylvainCorlay
